create table if not exists agencies (
    id          smallint      primary key generated always as identity,
    common_name varchar(128)  not null unique,
    full_name   varchar(128)  not null unique,
    acronym     varchar(8)    not null unique,
    url         varchar(2048) not null unique
);

--------------------------------------------------------------------------------

insert into agencies (common_name, full_name, acronym, url) values
    ('BSAC', 'British Sub Aqua Club', 'BSAC', 'https://www.bsac.com/'),
    ('GUE', 'Global Underwater Explorers', 'GUE', 'https://www.gue.com/'),
    ('NAUI', 'National Association of Underwater Instructors', 'NAUI', 'https://www.naui.org/'),
    ('PADI', 'Professional Association of Diving Instructors', 'PADI', 'https://www.padi.com/'),
    ('SDI', 'Scuba Diving International', 'SDI', 'https://www.tdisdi.com/sdi/'),
    ('SSI', 'Scuba Schools International', 'SSI', 'https://www.divessi.com/'),
    ('TDI', 'Technical Diving International', 'TDI', 'https://www.tdisdi.com/tdi/'),
    ('CMAS', 'Confédération Mondiale des Activités Subaquatiques', 'CMAS', 'https://www.cmas.org/');

--------------------------------------------------------------------------------

create table if not exists agency_courses (
    id                  smallint      primary key generated always as identity,
    agency_id           smallint      not null references agencies(id) on delete cascade,
    name                varchar(128)  not null,
    url                 varchar(2048) not null,
    is_specialty_course boolean       not null,
    is_tech_course      boolean       not null,
    is_pro_course       boolean       not null,
    unique(agency_id, name)
);

create index if not exists agency_courses_name_idx
    on agency_courses using gin (to_tsvector('simple', name));

create index if not exists agency_courses_agency_id_idx on agency_courses (agency_id);

--------------------------------------------------------------------------------

insert into agency_courses (
    agency_id, name, url, is_specialty_course, is_tech_course, is_pro_course
) values
-- BSAC
(1, 'Ocean Diver', 'https://www.bsac.com/page.asp?section=3303&sectionTitle=Ocean+Diver', FALSE, FALSE, FALSE),
(1, 'Sports Diver', 'https://www.bsac.com/page.asp?section=3305&sectionTitle=Sports+Diver', FALSE, FALSE, FALSE),
(1, 'Dive Leader', 'https://www.bsac.com/page.asp?section=3306&sectionTitle=Dive+Leader', FALSE, FALSE, TRUE),
--GUE
(2, 'Recreational Diver Level 1 - Nitrox Diver', 'http://gue.com/content/recreational-diver-level-1-nitrox-diver', FALSE, FALSE, FALSE),
(2, 'Recreational Diver Level 2 - Triox Diver', 'http://gue.com/content/recreational-diver-level-2-triox-diver', FALSE, FALSE, FALSE),
(2, 'Recreational Diver Level 3 - Trimix Diver', 'http://gue.com/content/recreational-diver-level-3-trimix-diver', FALSE, FALSE, FALSE),
(2, 'Doubles Primer', 'http://gue.com/content/doubles-course', FALSE, FALSE, FALSE),
(2, 'Drysuit Primer', 'http://gue.com/content/drysuit-course', FALSE, FALSE, FALSE),
(2, 'Gas Blender', 'http://gue.com/content/gas-blender', FALSE, FALSE, FALSE),
(2, 'Documentation Diver', 'http://gue.com/content/documentation-diver', FALSE, FALSE, FALSE),
(2, 'Diver Propulsion Vehicle Level 1', 'http://www.gue.com/content/diver-propulsion-vehicle-level-1', FALSE, FALSE, FALSE),
(2, 'Fundamentals Rec Pass', 'http://gue.com/content/gue-fundamentals', FALSE, FALSE, FALSE),
(2, 'Fundamentals Tec Pass', 'http://gue.com/content/gue-fundamentals', FALSE, TRUE, FALSE),
(2, 'Technical Diver Level 1', 'http://gue.com/training/gue-course-descriptions/technical/tech1', FALSE, TRUE, FALSE),
(2, 'Tech 60', 'http://gue.com/tech-60', FALSE, TRUE, FALSE),
(2, 'Technical Diver Level 2', 'http://gue.com/training/gue-course-descriptions/technical/tech2', FALSE, TRUE, FALSE),
(2, 'Rebreather Diver', 'http://gue.com/training/gue-course-descriptions/technical/rebreather-diver', FALSE, TRUE, FALSE),
(2, 'Cave Diver Level 1', 'http://gue.com/content/cave-diver-level-1', FALSE, TRUE, FALSE),
(2, 'Cave Diver Level 2', 'http://gue.com/content/cave-diver-level-2', FALSE, TRUE, FALSE),
(2, 'Underwater Cave Survey', 'http://gue.com/underwater-cave-survey', FALSE, TRUE, FALSE),
(2, 'Diver Propulsion Vehicle Cave', 'http://gue.com/diver-propulsion-vehicle-cave', FALSE, TRUE, FALSE),
-- PADI
(4, 'Discover Scuba Diving', 'https://www.padi.com/padi-courses/discover-scuba-diving/', FALSE, FALSE, FALSE),
(4, 'Scuba Diver', 'https://www.padi.com/padi-courses/scuba-diver/', FALSE, FALSE, FALSE),
(4, 'Open Water Diver', 'https://www.padi.com/padi-courses/open-water-diver/', FALSE, FALSE, FALSE),
(4, 'Advanced Open Water Diver', 'https://www.padi.com/padi-courses/advanced-open-water-diver-course/', FALSE, FALSE, FALSE),
(4, 'Rescue Diver', 'https://www.padi.com/padi-courses/rescue-diver-course/', FALSE, FALSE, FALSE),
(4, 'Divemaster', 'https://www.padi.com/padi-courses/divemaster-course/', FALSE, FALSE, TRUE),
(4, 'Assistant Instructor', 'https://www.padi.com/padi-courses/assistant-instructor-development-course/', FALSE, FALSE, TRUE),
(4, 'Open Water Scuba Instructor', 'https://www.padi.com/padi-courses/instructor-development-course-idc/', FALSE, FALSE, TRUE),
(4, 'Advanced Rebreather Diver', 'https://www.padi.com/padi-courses/advanced-rebreather-diver/', TRUE, FALSE, FALSE),
(4, 'Altitude Diver', 'https://www.padi.com/padi-courses/altitude-diver/', TRUE, FALSE, FALSE),
(4, 'AWARE - Fish Identification', 'https://www.padi.com/padi-courses/padi-course-aware-fish-identification/', TRUE, FALSE, FALSE),
(4, 'AWARE - Coral Reef Conservation Diver', 'https://www.padi.com/padi-courses/project-aware-coral-reef-conservation-course/', TRUE, FALSE, FALSE),
(4, 'Boat Diver', 'https://www.padi.com/padi-courses/boat-diver/', TRUE, FALSE, FALSE),
(4, 'Cavern Diver', 'https://www.padi.com/padi-courses/cavern-diver/', TRUE, FALSE, FALSE),
(4, 'Deep Diver', 'https://www.padi.com/padi-courses/deep-diver/', TRUE, FALSE, FALSE),
(4, 'Digital Underwater Photographer', 'https://www.padi.com/padi-courses/digital-underwater-photographer/', TRUE, FALSE, FALSE),
(4, 'Diver Propulsion Vehicle Diver', 'https://www.padi.com/padi-courses/diver-propulsion-vehicle/', TRUE, FALSE, FALSE),
(4, 'Discover Rebreather', 'https://www.padi.com/padi-courses/discover-rebreather-program-0', TRUE, FALSE, FALSE),
(4, 'Drift Diver', 'https://www.padi.com/padi-courses/drift-diver/', TRUE, FALSE, FALSE),
(4, 'Dry Suit Diver', 'https://www.padi.com/padi-courses/dry-suit-diver/', TRUE, FALSE, FALSE),
(4, 'Enriched Air Diver', 'https://www.padi.com/padi-courses/enriched-air-diver/', TRUE, FALSE, FALSE),
(4, 'Emergency Oxygen Provider', 'https://www.padi.com/padi-courses/emergency-oxygen-provider/', TRUE, FALSE, FALSE),
(4, 'Equipment Specialist', 'https://www.padi.com/padi-courses/equipment-specialist/', TRUE, FALSE, FALSE),
(4, 'Ice Diver', 'https://www.padi.com/padi-courses/ice-diver/', TRUE, FALSE, FALSE),
(4, 'Multilevel Diver', 'https://www.padi.com/padi-courses/multilevel-diver/', TRUE, FALSE, FALSE),
(4, 'Night Diver', 'https://www.padi.com/padi-courses/night-diver/', TRUE, FALSE, FALSE),
(4, 'Peak Performance Buoyancy', 'https://www.padi.com/padi-courses/peak-performance-buoyancy/', TRUE, FALSE, FALSE),
(4, 'Rebreather Diver', 'https://www.padi.com/padi-courses/rebreather-diver/', TRUE, FALSE, FALSE),
(4, 'Project AWARE® Specialist', 'https://www.padi.com/padi-courses/padi-course-project-aware-specialist/', TRUE, FALSE, FALSE),
(4, 'Public Safety Diver', 'https://www.padi.com/padi-courses/public-safety-diver/', TRUE, FALSE, FALSE),
(4, 'Search and Recovery Diver', 'https://www.padi.com/padi-courses/search-and-recovery-diver/', TRUE, FALSE, FALSE),
(4, 'Sidemount Diver', 'https://www.padi.com/padi-courses/sidemount-diver-scuba/', TRUE, FALSE, FALSE),
(4, 'Underwater Naturalist', 'https://www.padi.com/padi-courses/underwater-naturalist-course/', TRUE, FALSE, FALSE),
(4, 'Underwater Navigator', 'https://www.padi.com/padi-courses/underwater-navigator/', TRUE, FALSE, FALSE),
(4, 'Underwater Videographer', 'https://www.padi.com/padi-courses/underwater-videographer/', TRUE, FALSE, FALSE),
(4, 'Wreck Diver', 'https://www.padi.com/padi-courses/wreck-diver/', TRUE, FALSE, FALSE),
-- SDI
(5, 'Scuba Discovery Program', 'https://www.tdisdi.com/sdi/get-certified/scuba-discovery-program/', FALSE, FALSE, FALSE),
(5, 'Open Water Scuba Diver', 'https://www.tdisdi.com/sdi/get-certified/open-water-scuba-diver-course/', FALSE, FALSE, FALSE),
(5, 'Advanced Adventure Diver', 'https://www.tdisdi.com/sdi/get-certified/advanced-adventure-diver/', FALSE, FALSE, FALSE),
(5, 'Rescue Diver', 'https://www.tdisdi.com/sdi/get-certified/Rescue-Diver-Course/', FALSE, FALSE, FALSE),
(5, 'Divemaster', 'https://www.tdisdi.com/sdi/get-certified/Divemaster-Course/', FALSE, FALSE, TRUE),
(5, 'Assistant Instructor', 'https://www.tdisdi.com/sdi/get-certified/Assistant-Instructor-Course/', FALSE, FALSE, TRUE),
(5, 'Open Water Scuba Diver Instructor', 'https://www.tdisdi.com/sdi/get-certified/Instructor-Course/', FALSE, FALSE, TRUE),
(5, 'Advanced Buoyancy Diver', 'https://www.tdisdi.com/sdi/get-certified/advanced-buoyancy/', TRUE, FALSE, FALSE),
(5, 'Altitude Diver', 'https://www.tdisdi.com/sdi/get-certified/altitude-diver/', TRUE, FALSE, FALSE),
(5, 'Boat Diver', 'https://www.tdisdi.com/sdi/get-certified/boat-diver/', TRUE, FALSE, FALSE),
(5, 'Computer Diver', 'https://www.tdisdi.com/sdi/get-certified/Computer-Diver/', TRUE, FALSE, FALSE),
(5, 'Computer Nitrox Diver', 'https://www.tdisdi.com/sdi/get-certified/Computer-Nitrox-Diver/', TRUE, FALSE, FALSE),
(5, 'Deep Diver', 'https://www.tdisdi.com/sdi/get-certified/Deep-Diver/', TRUE, FALSE, FALSE),
(5, 'Diver Propulsion Vehicle Diver', 'https://www.tdisdi.com/sdi/get-certified/Diver-Propulsion-Vehicle/', TRUE, FALSE, FALSE),
(5, 'Drift Diver', 'https://www.tdisdi.com/sdi/get-certified/Drift-Diver/', TRUE, FALSE, FALSE),
(5, 'Dry Suit Diver', 'https://www.tdisdi.com/sdi/get-certified/Dry-Suit-Diver/', TRUE, FALSE, FALSE),
(5, 'Full Face Mask Diver', 'https://www.tdisdi.com/sdi/get-certified/Full-Face-Mask-Diver-Specialty/', TRUE, FALSE, FALSE),
(5, 'Ice Diver', 'https://www.tdisdi.com/sdi/get-certified/ice-diver/', TRUE, FALSE, FALSE),
(5, 'Marine Eco Systems Awareness Diver', 'https://www.tdisdi.com/sdi/get-certified/Marine-Ecosystems-Awareness/', TRUE, FALSE, FALSE),
(5, 'Night/Limited Visibility Diver', 'https://www.tdisdi.com/sdi/get-certified/Night-Limited-Visibility-Diver/', TRUE, FALSE, FALSE),
(5, 'Research Diver', 'https://www.tdisdi.com/sdi/get-certified/Research-Diver/', TRUE, FALSE, FALSE),
(5, 'Search and Recovery Diver', 'https://www.tdisdi.com/sdi/get-certified/search-recovery-diver/', TRUE, FALSE, FALSE),
(5, 'Shore and Beach Diver', 'https://www.tdisdi.com/sdi/get-certified/ShoreBeach-Diver/', TRUE, FALSE, FALSE),
(5, 'Sidemount Diver', 'https://www.tdisdi.com/courses/sdi-tdi-sidemount-diver/', TRUE, FALSE, FALSE),
(5, 'Solo Diver', 'https://www.tdisdi.com/sdi/get-certified/Solo-Diver-Course/', TRUE, FALSE, FALSE),
(5, 'Hunter/Collector Diver', 'https://www.tdisdi.com/sdi/get-certified/underwater-hunter-collector/', TRUE, FALSE, FALSE),
(5, 'Underwater Navigation', 'https://www.tdisdi.com/sdi/get-certified/Underwater-Navigation/', TRUE, FALSE, FALSE),
(5, 'Underwater Photographer Diver', 'https://www.tdisdi.com/sdi/get-certified/Underwater-Photography/', TRUE, FALSE, FALSE),
(5, 'Underwater Video Diver', 'https://www.tdisdi.com/sdi/get-certified/Underwater-Video/', TRUE, FALSE, FALSE),
(5, 'Wreck Diver', 'https://www.tdisdi.com/sdi/get-certified/Wreck-Diver/', TRUE, FALSE, FALSE),
-- SSI
(6, 'Try Scuba Diving', 'https://www.divessi.com/ts', FALSE, FALSE, FALSE),
(6, 'Open Water Diver', 'https://www.divessi.com/owd', FALSE, FALSE, FALSE),
(6, 'Advanced Adventurer', 'https://www.divessi.com/aa', FALSE, FALSE, FALSE),
(6, 'Dive Guide', 'https://www.divessi.com/dive_pro_ratings', FALSE, FALSE, TRUE),
(6, 'Divemaster', 'https://www.divessi.com/dive_pro_ratings', FALSE, FALSE, TRUE),
(6, 'Dive Control Specialist', 'https://www.divessi.com/dive_pro_ratings', FALSE, FALSE, TRUE),
(6, 'Training Specialist', 'https://www.divessi.com/dive_pro_ratings', FALSE, FALSE, TRUE),
(6, 'Open Water Instructor', 'https://www.divessi.com/instructor_levels', FALSE, FALSE, TRUE),
(6, 'Specialty Instructor', 'https://www.divessi.com/instructor_levels', FALSE, FALSE, TRUE),
(6, 'Advanced Open Water Instructor', 'https://www.divessi.com/instructor_levels', FALSE, FALSE, TRUE),
(6, 'Divemaster Instructor', 'https://www.divessi.com/instructor_levels', FALSE, FALSE, TRUE),
(6, 'Altitude Diving', 'https://www.divessi.com/sc-alt', TRUE, FALSE, FALSE),
(6, 'Boat Diving', 'https://www.divessi.com/sc-bd', TRUE, FALSE, FALSE),
(6, 'Dry Suit Diving', 'https://www.divessi.com/sc-dry', TRUE, FALSE, FALSE),
(6, 'Enriched Air Nitrox', 'https://www.divessi.com/sc-ean', TRUE, FALSE, FALSE),
(6, 'Equipment Techniques', 'https://www.divessi.com/sc-et', TRUE, FALSE, FALSE),
(6, 'Deep Diving', 'https://www.divessi.com/sc-dd', TRUE, FALSE, FALSE),
(6, 'Digital Underwater Photography', 'https://www.divessi.com/sc-dup', TRUE, FALSE, FALSE),
(6, 'Diver Stress and Rescue', 'https://www.divessi.com/sc-sr', TRUE, FALSE, FALSE),
(6, 'Navigation', 'https://www.divessi.com/sc-nv', TRUE, FALSE, FALSE),
(6, 'Night and Limited Visibility', 'https://www.divessi.com/sc-lv', TRUE, FALSE, FALSE),
(6, 'Perfect Buoyancy', 'https://www.divessi.com/sc-pb', TRUE, FALSE, FALSE),
(6, 'Recreation Sidemount', 'https://www.divessi.com/sc-side', TRUE, FALSE, FALSE),
(6, 'River Diving', 'https://www.divessi.com/sc-rvr', TRUE, FALSE, FALSE),
(6, 'Science of Diving', 'https://www.divessi.com/sc-sod', TRUE, FALSE, FALSE),
(6, 'Search and Recovery', 'https://www.divessi.com/sc-rec', TRUE, FALSE, FALSE),
(6, 'Shark Ecology', 'https://www.divessi.com/sc-sha', TRUE, FALSE, FALSE),
(6, 'Waves, Tides and Currents', 'https://www.divessi.com/sc-wtc', TRUE, FALSE, FALSE),
(6, 'Wreck Diving', 'https://www.divessi.com/sc-wr', TRUE, FALSE, FALSE),
-- TDI
(7, 'Intro to Tech Diving', 'https://www.tdisdi.com/tdi/get-certified/Intro-to-Tech-Diving/', FALSE, TRUE, FALSE),
(7, 'Nitrox Diver', 'https://www.tdisdi.com/tdi/get-certified/Nitrox-Diver/', FALSE, TRUE, FALSE),
(7, 'Advanced Nitrox Diver', 'https://www.tdisdi.com/tdi/get-certified/Advanced-Nitrox-Diver/', FALSE, TRUE, FALSE),
(7, 'Semi-closed Circuit Rebreather Diver', 'https://www.tdisdi.com/tdi/get-certified/semi-closed-rebreather-diver-dolphin-ray-submatix-st100-azmuth/', FALSE, TRUE, FALSE),
(7, 'Helitrox Diver', 'https://www.tdisdi.com/tdi/get-certified/helitrox-diver-course/', FALSE, TRUE, FALSE),
(7, 'Decompression Procedures Diver', 'https://www.tdisdi.com/tdi/get-certified/Decompression-Procedures-Diver/', FALSE, TRUE, FALSE),
(7, 'Extended Range Diver', 'https://www.tdisdi.com/tdi/get-certified/Extended-Range-Diver/', FALSE, TRUE, FALSE),
(7, 'Trimix Diver', 'https://www.tdisdi.com/tdi/get-certified/Trimix-Diver/', FALSE, TRUE, FALSE),
(7, 'Advanced Trimix Diver', 'https://www.tdisdi.com/tdi/get-certified/Advanced-Trimix-Diver/', FALSE, TRUE, FALSE),
(7, 'CCR Air Diluent Diver', 'https://www.tdisdi.com/tdi/get-certified/air-diluent-closed-circuit-rebreather-diver-course/', FALSE, TRUE, FALSE),
(7, 'CCR Air Diluent Decompression Procedures Diver', 'https://www.tdisdi.com/tdi/get-certified/air-diluent-closed-circuit-rebreather-decompression-procedures-diver-course/', FALSE, TRUE, FALSE),
(7, 'CCR Helitrox Decompression Procedures Diver', 'https://www.tdisdi.com/tdi/get-certified/helitrox-ccr-diver/', FALSE, TRUE, FALSE),
(7, 'CCR Mixed Gas Diver', 'https://www.tdisdi.com/tdi/get-certified/mixed-gas-closed-circuit-rebreather-diver-course/', FALSE, TRUE, FALSE),
(7, 'Advanced Mixed Gas CCR Diver', 'https://www.tdisdi.com/tdi/get-certified/advanced-mix-gas-closed-circuit-rebreather-diver-course/', FALSE, TRUE, FALSE),
(7, 'Cavern Diver', 'https://www.tdisdi.com/tdi/get-certified/Cavern-Diver/', FALSE, TRUE, FALSE),
(7, 'Intro to Cave Diver', 'https://www.tdisdi.com/tdi/get-certified/intro-to-cave-diver/', FALSE, TRUE, FALSE),
(7, 'Full Cave Diver', 'https://www.tdisdi.com/tdi/get-certified/full-cave-diver/', FALSE, TRUE, FALSE),
(7, 'Rebreather Cavern Diver', 'https://www.tdisdi.com/tdi/get-certified/rebreather-cavern-diver-2/', FALSE, TRUE, FALSE),
(7, 'Rebreather Intro Cave Diver', 'https://www.tdisdi.com/tdi/get-certified/rebreather-intro-cave-diver/', FALSE, TRUE, FALSE),
(7, 'Rebreather Full Cave Diver', 'https://www.tdisdi.com/tdi/get-certified/rebreather-full-cave-diver/', FALSE, TRUE, FALSE),
(7, 'Advanced Wreck Diver', 'https://www.tdisdi.com/tdi/get-certified/Advanced-Wreck-Diver/', TRUE, TRUE, FALSE),
(7, 'Cave Surveying Diver', 'https://www.tdisdi.com/tdi/get-certified/Cave-Surveying-Diver/', TRUE, TRUE, FALSE),
(7, 'Diver Propulsion Vehicle (DPV) Diver', 'https://www.tdisdi.com/tdi/get-certified/Cave-DPV-Diver/', TRUE, TRUE, FALSE),
(7, 'Mine Diver Level 1', 'https://www.tdisdi.com/tdi/get-certified/mine-diver1/', TRUE, TRUE, FALSE),
(7, 'Mine Diver Level 2', 'https://www.tdisdi.com/tdi/get-certified/mine-diver2/', TRUE, TRUE, FALSE),
(7, 'Sidemount Diver', 'https://www.tdisdi.com/courses/sdi-tdi-sidemount-diver/', TRUE, TRUE, FALSE),
(7, 'Stage Cave Diver', 'https://www.tdisdi.com/tdi/get-certified/Stage-Cave-Diver/', TRUE, TRUE, FALSE),
(7, 'Cave DPV Diver', 'https://www.tdisdi.com/tdi/get-certified/tdi-dpv-cave-diver/', TRUE, TRUE, FALSE),
(7, 'Non-Diving Specialty Instructor', 'https://www.tdisdi.com/tdi/get-certified/non-diving-specialty-instructor/', FALSE, TRUE, TRUE),
(7, 'Technical Divemaster', 'https://www.tdisdi.com/tdi/get-certified/technical-divemaster/', FALSE, TRUE, TRUE),
(7, 'Instructor', 'https://www.tdisdi.com/tdi/get-certified/tdi-leadership-courses/', FALSE, TRUE, TRUE),
(7, 'Instructor Trainer', 'https://www.tdisdi.com/tdi/get-certified/TDI-Instructor-Trainer-Course/', FALSE, TRUE, TRUE),
(6, 'React Right', 'https://info.divessi.com/en/scuba-diving/advanced-scuba-training/emergency-training/react-right-129.html', TRUE, FALSE, FALSE);

